In [2]:
import numpy as np

In [8]:
vector=np.zeros(10)
vector[4]=1
print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [42]:
a=int(input("enter number a"))
b=int(input("enter number b"))
ran=np.random.randint(0,101,size=(a,b))
print("the array is ",ran)
avg=np.mean(ran)
print("the average is ",avg)

enter number a 2
enter number b 3


the array is  [[ 9  6 83]
 [82 43 60]]
the average is  47.166666666666664


In [46]:
arr=np.random.randint(0,2,size=10)
print(arr)

[1 0 1 1 1 0 0 0 0 0]


In [60]:
id=np.identity(3,dtype=int)
print(id)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [64]:
arr=np.random.randint(0,4,size=(5,5))
print(arr)

[[3 3 2 1 3]
 [0 0 3 1 0]
 [3 0 1 2 1]
 [2 0 1 1 0]
 [2 2 1 3 2]]


In [26]:
arr=[]
for x in range(0,10):
    arr.append(int(input("Enter numbers:")))

Enter numbers: 90
Enter numbers: 1
Enter numbers: 2
Enter numbers: 3
Enter numbers: 4
Enter numbers: 5
Enter numbers: 6
Enter numbers: 7
Enter numbers: 8
Enter numbers: 9


In [40]:
import numpy as np
arr=np.array(arr)
print(arr[2:6])
print(arr[5:9])
print(arr[2:10])

[2 3 4 5]
[5 6 7 8]
[2 3 4 5 6 7 8 9]


In [76]:
arr=np.random.randint(1,100,10)
arr.sort()

In [78]:
arr.reshape(5,2)

array([[ 4, 36],
       [45, 62],
       [62, 65],
       [78, 83],
       [91, 99]])